apiVersion: v1
kind: Service
metadata:
  name: htcondor-cm-service
  labels:
    app: htcondor-cm
spec:
  type: ClusterIP
  ipFamilyPolicy: RequireDualStack
  ipFamilies:
  - IPv6
  - IPv4
  ports:
    - port: 9618
      protocol: TCP
      targetPort: 9618
      name: htcondor
    - port: 51450
      protocol: TCP
      targetPort: 51450
      name: htcondor-ha
    - port: 41450
      protocol: TCP
      targetPort: 41450
      name: htcondor-replication
  selector:
    app: htcondor-cm
  externalIPs:
  - {{ .Values.hostIPv4 }}
  - {{ .Values.hostIPv6 }}

